version: "3.1"

networks:
  app-tier:
    driver: bridge
services:
  mysql:
    networks:
      - app-tier
    image: "mysql/mysql-server:5.7"
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=autoin102030
      - MYSQL_USER=autoin
      - MYSQL_PASSWORD=autoin2021
      - MYSQL_DATABASE=autoinven
  nodejs:
    environment:
      MYSQL_HOST_IP: mysql # the name of mysql service in your docker-compose, which will get resolved to the internal IP of the mysql container
    networks:
      - app-tier
    build:
      context: .
 #     dockerfile: ./dockerfile
    restart: always
    ports:
      - "5000:5000"
    links:
      - mysql
    depends_on:
      - mysql
    container_name: autoinven
